### ISSUE TITLE
Implementing MDAnalysis converters

### ISSUE THREAD

**Issue by IAlibay** [MolSSI/MMElemental#1]
As discussed off-github, it would be great to get MDAnalysis and MMElemental talking.

I'm opening this issue to look into what needs to be addressed in order to implement such a converter.

The main question which was raised off-github relates to the issue of licenses:
 - Can non-GPL code import a module from a GPL codebase?

From discussions with @Andrew-AbiMansour it seems like the answer here is "probably". It might be worth exploring this further, especially if there's anyone here that knows about the details of open source licensing law?

Pinging @lilyminium @orbeckst and @fiona-naughton who also attended the meeting.

**Comment by orbeckst** [comment]
When it comes to law, there’s little point in non-lawyers debating it when you need an actual answer so I suggest, MolSSI figures it out or we ask NumFOCUS.

**Comment by IAlibay** [comment]
From a practical view (going by the parmed converter) implementing a `UniverseToMolecule` should be as simple as looping through the appropriate `Universe` attributes. The main concern here is dealing with trajectory data, it doesn't seem like MMElemental currently handles more than a single frame of information. We'd probably have to set things up in such a way as to request new frames from the `Universe` object (instead of holding all the data in memory).

I've not given much through into `MoleculeToUniverse`, this should probably be a case of using MDA's memory reader (in the same way that MDA does converters).

**Comment by anabiman** [comment]
There is no schema yet for any output files in MMElemental, so trajectories are not yet supported. For now, we can just focus on structures / single frame including topology (but not force field params).

**Comment by anabiman** [comment]
[This](https://github.com/MolSSI/MMElemental/blob/master/mmelemental/components/mda_component.py) is more or less a skeletal version of what I think an MDA structure converter would look like. Not sure if Universe or AtomGroup is what we should be using here?

**Comment by anabiman** [comment]
MDAnalysis/MMSchema converter moved to a separate repo: [mmic_mda](https://github.com/MolSSI/mmic_mda)
